### Pega todos os cliente e seus pets
GET http://localhost:3003/admin/clients


### Registra cliente e pet
POST http://localhost:3003/admin/client/register
Content-Type: application/json

{
  "client": {
    "nome": "cebola",
    "telefone": "28999343577"
  },
  "pet": {
    "idade": 5,
    "nome": "cebolinha",
    "raca": "vira-lata",
    "tipo": "CACHORRO"
  }
}

### Mudando algum dado
PATCH http://localhost:3003/admin/client/7542be8e-959f-47de-b2ed-e098c7316123
Content-Type: application/json

{
  "telefone": "11999777132"
  
}


### Deleta o usuario
DELETE http://localhost:3003/admin/client
Content-Type: application/json

{
    "id": "b7bbca37-1737-4409-aa26-32a8ef65a111"
}

